### ISSUE TITLE
Use media content URI directly vs. construction using ID

### ISSUE THREAD

**Issue by grokify** [tylerlong/ringcentral-js-concise#1]
When retrieving media content, the full URI returned by the API should be used, vs. constructing it manually. This is because the content URI structure can change.

For example, the following code

https://github.com/tylerlong/ringcentral-js-concise/blob/fecf1194d16ddd484a49ad39b9170aab5f0edc8d/test/download_fax.spec.js#L27

should be updated to something like:

```
r = await rc.get(lastFax.attachments[0].uri)
```

This will have the request use the correct hostname, e.g. `media.devtest.ringcentral.com` vs. `platform.devtest.ringcentral.com`. The access token is still needed when accessing the `media` host.

**Comment by tylerlong** [comment]
Yes, what you said makes sense. 

But up til now `platform.devtest.ringcentral.com` works for media content too. I tested both production and sandbox.

Most of RingCentral's SDK assume that all the API calls using the same domain name.  Let me think what I can do.

**Comment by tylerlong** [comment]
Fixed.
